name: CI - MacOS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ci-system-test

env:
    BUILD_TYPE: Release

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './Team41/Code41/src'
        exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: google
        
  build-mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team41/Code41/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project on Mac
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
          
      - name: Run Unit Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/unit_testing
          ./unit_testing
          
      - name: Run Integration Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/integration_testing
          ./integration_testing
          
      - name: Run Sample System Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/autotester
          ./autotester $GITHUB_WORKSPACE/Team41/Code41/tests/Sample_source.txt $GITHUB_WORKSPACE/Team41/Code41/tests/Sample_queries.txt $GITHUB_WORKSPACE/Team41/Code41/tests/out.xml
          
      - name: Run System Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
           cd ../build/src/autotester
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/affects/simple_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/affects/simple_one_affects_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/affects-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/affects/simple_source_2.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/affects/simple_2_one_affects_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/affects-2-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/basic-spa/deep_nesting_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/basic-spa/deep_nesting_multiple_clauses_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/basic-spa-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/calls/multiple_procedures_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/calls/multiple_procedures_one_calls_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/calls-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/multi-clause/deep_nesting_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/multi-clause/deep_nesting_multiple_clauses_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/multiple-clauses-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/next/deep_nesting_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/next/deep_nesting_one_next_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/next-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/next/deep_nesting_source_2.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/next/deep_nesting_2_one_next_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/next-2-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/pattern/container_patterns_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/pattern/container_patterns_one_pattern_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/pattern-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/pattern/stress_patterns_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/pattern/stress_patterns_one_pattern_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/pattern-stress-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/stress/deep_nesting_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/stress/stress_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/stress-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/with/deep_nesting_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/with/deep_nesting_one_with_clause_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/with-analysis.xml
            ./autotester $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/cache/test_cache_source.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/cache/test_cache_queries.txt $GITHUB_WORKSPACE/Team41/Tests41/milestone-2/milestone-2-out/cache-analysis.xml
                   
      - name: Setup Python Version For Checking System Tests
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Check System Tests
        working-directory: ${{github.workspace}}
        shell: python
        run: | 
            python $GITHUB_WORKSPACE/Team41/Tests41/check-system-test.py