name: CI - MacOS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
    BUILD_TYPE: Release

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './Team41/Code41/src'
        exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: google
        
  build-mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team41/Code41/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project on Mac
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
          
      - name: Run Unit Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/unit_testing
          ./unit_testing
          
      - name: Run Integration Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/integration_testing
          ./integration_testing
          
      - name: Run Sample System Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
           cd ../build/src/autotester
           ./autotester $GITHUB_WORKSPACE/Team41/Code41/tests/Sample_source.txt $GITHUB_WORKSPACE/Team41/Code41/tests/Sample_queries.txt $GITHUB_WORKSPACE/Team41/Code41/tests/out.xml
         
      - name: Run System Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          $GITHUB_WORKSPACE/Team41/Tests41/run-system-test.sh  $GITHUB_WORKSPACE
                   
      - name: Setup Python Version For Checking System Tests
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
    
      - name: Run System Tests Check
        working-directory: ${{github.workspace}}
        run: python $GITHUB_WORKSPACE/Team41/Tests41/check-system-test.py $GITHUB_WORKSPACE
        
        
      - name: Archive Milestone 1 System Test Results
        uses: actions/upload-artifact@v3
        with:
          name: milestone-1-system-test-results
          path: |
            ${{github.workspace}}/Team41/Tests41/milestone-1/system-test-out
           
      - name: Archive Milestone 2 System Test Results
        uses: actions/upload-artifact@v3
        with:
          name: milestone-2-system-test-results
          path: |
            ${{github.workspace}}/Team41/Tests41/milestone-2/milestone-2-out
            
      - name: Evaulate System Tests Check
        run: |
            if [[ ${{ env.check_status }} == fail ]]; 
            then 
            echo ${{env.fail_message}}
            exit 1; 
            else
            echo ${{env.pass_message}}            
            exit 0; fi
            
     