name: CI for Cmake Project - MacOS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
    BUILD_TYPE: Release

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './Team41/Code41/src'
        exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: google
        
  build-mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team41/Code41/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project on Mac
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
          
      - name: Run Unit Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/unit_testing
          ./unit_testing
          
      - name: Run Integration Tests
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cd ../build/src/integration_testing
          ./integration_testing
